### PR TITLE
Run in unsupported architectures

### LINKED ISSUE #21: Fails in unsupported architecture
I'm playing with this in RISC-V, running it in [qemu](https://collective.flashbots.net/t/risc-v-cheat-sheet/3820#p-8094-qemu-1), and getting this error:

```
$ go build .
# github.com/prysmaticlabs/gohashtree
./hash.go:46:5: undefined: supportedCPU
./hash.go:56:5: undefined: supportedCPU
./hash.go:86:5: undefined: supportedCPU
```

### PR DESCRIPTION
**Pull request by come-maiz**
Fixes #21.

### CODE REVIEW

**Comment by prestonvanloon** [comment]
How would this work? If you aren't building for amd64 or arm64, what assembly file would the compiler use?

File: hash.go [hunk 1]
```diff
@@ -28,8 +28,6 @@ import (
 	"unsafe"
 )
 
-func _hash(digests *byte, p [][32]byte, count uint32)
```
Comment (prestonvanloon) [inline hash.go:31]: Why move this?

**Comment by come-maiz** [comment]
> How would this work? If you aren't building for amd64 or arm64, what assembly file would the compiler use?

It uses sha256_1_generic.

File: hash.go (hunk 1 above)
Comment (come-maiz) [reply hash.go:31]: To make space for an empty implementation in the hash_unsupported. Otherwise there would be two declarations of this function.

**Review by potuz — COMMENTED** [review]
Nice thanks for the PR, I assume this would be triggered for RISCV, would you care to add a CI evaluator that would run on RISCV and fail without this PR? You can look in the  github workflow of this same repo for it.

**Comment by come-maiz** [comment]
> would you care to add a CI evaluator that would run on RISCV and fail without this PR? 

What about this? https://github.com/prysmaticlabs/gohashtree/pull/23/files

**Review by potuz — APPROVED** [review]
Thanks so much for this PR @come-maiz ! 

I've run the tests locally, with and without the PR and also ran them on qemu without the workflow.

**Comment by come-maiz** [comment]
Thank you @prestonvanloon and @potuz .
